# Dependencies
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink: /:slug.html

# Setup
title:            Artem Konovalov
tagline: |
  posts on JVM based languages, concurrent programming, 
  functional programming and stuff
description: |
  This website is a personal blog. Mainly there are
  posts about java, but you can find ones on other topics.
url:              https://izebit.ru
baseurl:          /

author:
  name:  'Artem Konovalov'
  email: izebit@gmail.com

linkedin: https://www.linkedin.com/in/conovart/
github: https://github.com/izebit
stackoverflow: https://ru.stackoverflow.com/users/10353/artem
certificates: https://www.credly.com/users/artem-konovalov/badges


paginate:         5

