# Dependencies
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Permalinks
permalink: /:slug.html

# Setup
title:            Artem Konovalov
tagline: |
  posts on JVM based languages, concurrent programming, 
  functional programming and stuff
description: |
  This website is a personal blog. Mainly there are
  posts about java, but you can find ones on other topics.
url:              https://izebit.ru
baseurl:          /

author:
  name:  'Artem Konovalov'
  email: izebit@gmail.com

linkedin: https://www.linkedin.com/in/conovart/
github: https://github.com/izebit
stackoverflow: https://ru.stackoverflow.com/users/10353/artem
certificates: https://www.credly.com/users/artem-konovalov/badges

social:
  name: Artem Konovalov
  links:
    - https://www.linkedin.com/in/conovart/
    - https://github.com/izebit
    - https://izebit.ru

logo: /assets/logos/photos/main-thumbnail.jpg

webmaster_verifications:
  google: MGhCSoTWiTCeUdZ_2tNyZZ5dmg8Yn18pjFuo9HhksIw
  yandex: 34c428376cb827b4

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

